USE DataWarehouse;

-- Explore All Objects in the Database
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--************************************--

-- Dimension Exploration

---- Customers Dimensions
SELECT * FROM gold.dim_customers
SELECT DISTINCT country FROM gold.dim_customers

---- Products Dimensions
SELECT * FROM gold.dim_products
SELECT DISTINCT category, subcategory FROM gold.dim_products
SELECT DISTINCT 
	category, subcategory, product_name 
FROM 
gold.dim_products
ORDER BY 1,2,3

--************************************--

-- DATE Exploration 
--- * Identify the earliest and latest dates (boundaries)
--- * Understand the scope of data and timespan ( do we have 2 years or 10 years?)

---- Customers Dates
SELECT * FROM gold.dim_customers
SELECT DATEDIFF(year, MIN(birthdate), CAST(GETDATE() AS DATE)), DATEDIFF(year, MAX(birthdate), CAST(GETDATE() AS DATE))
FROM gold.dim_customers

---- Sales Dates
SELECT * FROM gold.fact_sales
SELECT MIN(order_date), MAX(order_date), DATEDIFF(year, MIN(order_date), MAX(order_date))
FROM gold.fact_sales

--************************************--

-- Measures Exploration
--- Calculate the key metrics of the business (Calculate the highest and lowest level of aggregation)

--- Total Sales
SELECT * FROM gold.fact_sales

SELECT FORMAT(SUM(sales_amount), 'N') AS TotalSales
FROM gold.fact_sales

--- Total Quantity
SELECT FORMAT(SUM(quantity), 'N') AS TotalQuantity
FROM gold.fact_sales

--- Average Selling price
SELECT FORMAT(AVG(price), 'N') AS AvgPrice
FROM gold.fact_sales

--- Total Of Orders
SELECT  FORMAT(COUNT(DISTINCT order_number), 'N0') AS total_orders_number
FROM gold.fact_sales

--- Total Of Products
SELECT * FROM gold.dim_products

SELECT DISTINCT FORMAT(COUNT(product_key), 'N0') AS total_products_number
FROM gold.dim_products

--- Total Of customers
SELECT * FROM gold.dim_customers

SELECT FORMAT(COUNT(customer_key), 'N0') AS total_customers_number
FROM gold.dim_customers

--- Total Of customers that has placed an order
SELECT COUNT(DISTINCT customer_key) AS total_customers_placed_order
FROM gold.fact_sales 

------ ****** The big picture about the key metrics ****** ------

SELECT 'Total Sales' AS measure_name, FORMAT(SUM(sales_amount), 'N') AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total quantity', FORMAT(SUM(quantity), 'N0') FROM gold.fact_sales
UNION ALL
SELECT 'Average Selling price', FORMAT(AVG(price), 'N') FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', FORMAT(COUNT(DISTINCT order_number), 'N0') FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', FORMAT(COUNT(product_key), 'N0') FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', FORMAT(COUNT(customer_key), 'N0') FROM gold.dim_customers

------ ****** Magnitude ****** ------

---- Find total customers by countries

SELECT 
country, COUNT(customer_key) AS total_customers_by_country
FROM gold.dim_customers
Group by country
ORDER BY total_customers_by_country DESC

---- Find total customers by gender

SELECT 
gender, COUNT(customer_key) AS total_customers_by_gender
FROM gold.dim_customers
Group by gender
ORDER BY total_customers_by_gender DESC

---- Find total products by category

SELECT 
category, COUNT(product_key) AS total_products_by_category
FROM gold.dim_products
Group by category
ORDER BY total_products_by_category DESC

---- What is the average costs in each category?

SELECT 
category, AVG(cost) AS average_costs_by_category
FROM gold.dim_products
Group by category
ORDER BY average_costs_by_category DESC

---- What is the total revenue generated for each category?

SELECT 
 p.category, SUM(s.sales_amount) total_rev_by_category
FROM gold.fact_sales s
LEFT JOIN  gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_rev_by_category DESC

---- Find total revenue is generated by each customer

SELECT 
 c.customer_key, c.first_name, c.last_name, SUM(Coalesce(s.sales_amount, 0)) AS total_customer_rev
FROM gold.fact_sales s
LEFT JOIN  gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY  c.customer_key, c.first_name, c.last_name
ORDER BY total_customer_rev DESC

---- What is the distribution of sold items across countries?

SELECT 
  c.country, SUM(Coalesce(s.quantity, 0)) AS total_customer_rev_by_country
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_customer_rev_by_country DESC

------ ****** Ranking ****** ------

---- Which 5 products generate the highest revenue?

SELECT top 5
	p.product_name, 
	SUM(s.sales_amount) total_rev_by_product
	, ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount) DESC) AS RANK_
FROM gold.fact_sales s
LEFT JOIN  gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.product_name

---- What are the 5 worst-performing products in terms of sales?

SELECT top 5
	p.product_name, 
	SUM(s.sales_amount) total_rev_by_product
	, ROW_NUMBER() OVER(ORDER BY SUM(s.sales_amount)) AS RANK_
FROM gold.fact_sales s
LEFT JOIN  gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.product_name
